### ISSUE TITLE
Connection to Firefox is timing out after 30000ms

### ISSUE THREAD

**Issue by Khrove** [aslushnikov/ispuppeteerfirefoxready#2]
`(node:7956) UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to Firefox!
    at Timeout.onTimeout (C:\Users\josjohnson\Desktop\projects\test-puppeteer\node_modules\puppeteer-firefox\lib\Launcher.js:272:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  -- ASYNC --
    at Puppeteer.<anonymous> (C:\Users\josjohnson\Desktop\projects\test-puppeteer\node_modules\puppeteer-firefox\lib\helper.js:31:27)
    at C:\Users\josjohnson\Desktop\projects\test-puppeteer\firefox-test.js:4:37
    at Object.<anonymous> (C:\Users\josjohnson\Desktop\projects\test-puppeteer\firefox-test.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
(node:7956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Just downloaded puppeteer-firefox (maybe 20 minutes ago) and tried to run using the example provided on the experimental/puppeteer-firefox Github. Receiving the above error. Let me know if you need anything else provided. 

I have the current version of Firefox downloaded locally along with the custom build version so not sure if that could cause this?

**Comment by aslushnikov** [comment]
Do you try to connect to the current version of Firefox or to the one that comes with puppeteer-firefox?

**Comment by Khrove** [comment]
@aslushnikov I believe the one that comes with puppeteer-firefox. I did not explicitly say anywhere to use either one so I assume the library defaults to the custom one?

Also a few more notes that I neglected to add. I was running this yesterday on my work laptop which is behind a corporate firewall (obviously). Last night I tried running it on my home desktop without strict security policies and everything ran fine.

That being said do you have any tips and tricks in how to run this behind a strict firewall/policies?

**Comment by aslushnikov** [comment]
> That being said do you have any tips and tricks in how to run this behind a strict firewall/policies?

It looks like our custom firefox build was prevented from launching. Is there any place where you can setup an exception for the browser from the `node_modules/puppeteer-firefox` folder?

**Comment by Khrove** [comment]
I brought up your suggestion to my companies sys admins and they decided to go with elevated privileges. With the elevated privileges Firefox is now opening so this issue can be closed.

Thanks for the suggestion!
